// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXlb8Kd4u8tPyluaz1kYZW-SNeBcdhAM',
    appId: '1:498414042729:web:56bfaeff27cc8acb77ecf8',
    messagingSenderId: '498414042729',
    projectId: 'mental-wellness-b61b8',
    authDomain: 'mental-wellness-b61b8.firebaseapp.com',
    databaseURL: 'https://mental-wellness-b61b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mental-wellness-b61b8.appspot.com',
    measurementId: 'G-PR1XK396DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXAScybQWSiF-xdpcGuaVkEMTHIpJC0SM',
    appId: '1:498414042729:android:04af829a7296a41577ecf8',
    messagingSenderId: '498414042729',
    projectId: 'mental-wellness-b61b8',
    databaseURL: 'https://mental-wellness-b61b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mental-wellness-b61b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxqv3FYH5BPBvZ7J6Np1cU6YvlmrEjpU',
    appId: '1:498414042729:ios:74ffc8e1147700a477ecf8',
    messagingSenderId: '498414042729',
    projectId: 'mental-wellness-b61b8',
    databaseURL: 'https://mental-wellness-b61b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mental-wellness-b61b8.appspot.com',
    iosBundleId: 'com.example.flutterMentalWellness',
  );
}
